GET http://127.0.0.1:8080/api/v1/hello

###
GET http://127.0.0.1:8080/api/v1/hello/max

###
GET http://127.0.0.1:8080/api/v1/hello/%20

###
GET http://127.0.0.1:8080/health

###
GET http://127.0.0.1:8080/openapi

###
GET http://127.0.0.1:8080/metrics
Accept: application/json

###
POST http://127.0.0.1:8080/api/v1/price
Content-Type: application/json
Accept: application/json

{
  "value": 12.09
}

###
